version: 2

jobs:
  build:
    working_directory: /go/src/github.com/mathetake/gann
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build .
